# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrew/VSCode-workspace/CS301_Bootcamp_Topics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrew/VSCode-workspace/CS301_Bootcamp_Topics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrew/VSCode-workspace/CS301_Bootcamp_Topics/CMakeFiles /Users/andrew/VSCode-workspace/CS301_Bootcamp_Topics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrew/VSCode-workspace/CS301_Bootcamp_Topics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named catch2_main_DO_NOT_RUN

# Build rule for target.
catch2_main_DO_NOT_RUN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 catch2_main_DO_NOT_RUN
.PHONY : catch2_main_DO_NOT_RUN

# fast build rule for target.
catch2_main_DO_NOT_RUN/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catch2_main_DO_NOT_RUN.dir/build.make CMakeFiles/catch2_main_DO_NOT_RUN.dir/build
.PHONY : catch2_main_DO_NOT_RUN/fast

#=============================================================================
# Target rules for targets named _Hello_World_IDE_Test_

# Build rule for target.
_Hello_World_IDE_Test_: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _Hello_World_IDE_Test_
.PHONY : _Hello_World_IDE_Test_

# fast build rule for target.
_Hello_World_IDE_Test_/fast:
	$(MAKE) $(MAKESILENT) -f "_IDE Hello World Test/CMakeFiles/_Hello_World_IDE_Test_.dir/build.make" "_IDE Hello World Test/CMakeFiles/_Hello_World_IDE_Test_.dir/build"
.PHONY : _Hello_World_IDE_Test_/fast

#=============================================================================
# Target rules for targets named Basic_Input_Output

# Build rule for target.
Basic_Input_Output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Basic_Input_Output
.PHONY : Basic_Input_Output

# fast build rule for target.
Basic_Input_Output/fast:
	$(MAKE) $(MAKESILENT) -f "cin cout getline/CMakeFiles/Basic_Input_Output.dir/build.make" "cin cout getline/CMakeFiles/Basic_Input_Output.dir/build"
.PHONY : Basic_Input_Output/fast

#=============================================================================
# Target rules for targets named cin_cout_Exercise_1

# Build rule for target.
cin_cout_Exercise_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cin_cout_Exercise_1
.PHONY : cin_cout_Exercise_1

# fast build rule for target.
cin_cout_Exercise_1/fast:
	$(MAKE) $(MAKESILENT) -f "cin cout getline/CMakeFiles/cin_cout_Exercise_1.dir/build.make" "cin cout getline/CMakeFiles/cin_cout_Exercise_1.dir/build"
.PHONY : cin_cout_Exercise_1/fast

#=============================================================================
# Target rules for targets named cin_cout_Exercise_2

# Build rule for target.
cin_cout_Exercise_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cin_cout_Exercise_2
.PHONY : cin_cout_Exercise_2

# fast build rule for target.
cin_cout_Exercise_2/fast:
	$(MAKE) $(MAKESILENT) -f "cin cout getline/CMakeFiles/cin_cout_Exercise_2.dir/build.make" "cin cout getline/CMakeFiles/cin_cout_Exercise_2.dir/build"
.PHONY : cin_cout_Exercise_2/fast

#=============================================================================
# Target rules for targets named Types_and_Casting_Examples

# Build rule for target.
Types_and_Casting_Examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Types_and_Casting_Examples
.PHONY : Types_and_Casting_Examples

# fast build rule for target.
Types_and_Casting_Examples/fast:
	$(MAKE) $(MAKESILENT) -f "Types and Casting/CMakeFiles/Types_and_Casting_Examples.dir/build.make" "Types and Casting/CMakeFiles/Types_and_Casting_Examples.dir/build"
.PHONY : Types_and_Casting_Examples/fast

#=============================================================================
# Target rules for targets named Types_and_Casting_Debugger_Example

# Build rule for target.
Types_and_Casting_Debugger_Example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Types_and_Casting_Debugger_Example
.PHONY : Types_and_Casting_Debugger_Example

# fast build rule for target.
Types_and_Casting_Debugger_Example/fast:
	$(MAKE) $(MAKESILENT) -f "Types and Casting/CMakeFiles/Types_and_Casting_Debugger_Example.dir/build.make" "Types and Casting/CMakeFiles/Types_and_Casting_Debugger_Example.dir/build"
.PHONY : Types_and_Casting_Debugger_Example/fast

#=============================================================================
# Target rules for targets named String_Examples

# Build rule for target.
String_Examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 String_Examples
.PHONY : String_Examples

# fast build rule for target.
String_Examples/fast:
	$(MAKE) $(MAKESILENT) -f Strings/CMakeFiles/String_Examples.dir/build.make Strings/CMakeFiles/String_Examples.dir/build
.PHONY : String_Examples/fast

#=============================================================================
# Target rules for targets named String_cstring_Examples

# Build rule for target.
String_cstring_Examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 String_cstring_Examples
.PHONY : String_cstring_Examples

# fast build rule for target.
String_cstring_Examples/fast:
	$(MAKE) $(MAKESILENT) -f Strings/CMakeFiles/String_cstring_Examples.dir/build.make Strings/CMakeFiles/String_cstring_Examples.dir/build
.PHONY : String_cstring_Examples/fast

#=============================================================================
# Target rules for targets named String_Practice_Basic_Tests

# Build rule for target.
String_Practice_Basic_Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 String_Practice_Basic_Tests
.PHONY : String_Practice_Basic_Tests

# fast build rule for target.
String_Practice_Basic_Tests/fast:
	$(MAKE) $(MAKESILENT) -f Strings/CMakeFiles/String_Practice_Basic_Tests.dir/build.make Strings/CMakeFiles/String_Practice_Basic_Tests.dir/build
.PHONY : String_Practice_Basic_Tests/fast

#=============================================================================
# Target rules for targets named String_Practice_Unit_Tests

# Build rule for target.
String_Practice_Unit_Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 String_Practice_Unit_Tests
.PHONY : String_Practice_Unit_Tests

# fast build rule for target.
String_Practice_Unit_Tests/fast:
	$(MAKE) $(MAKESILENT) -f Strings/CMakeFiles/String_Practice_Unit_Tests.dir/build.make Strings/CMakeFiles/String_Practice_Unit_Tests.dir/build
.PHONY : String_Practice_Unit_Tests/fast

#=============================================================================
# Target rules for targets named Scope_Example_1

# Build rule for target.
Scope_Example_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Scope_Example_1
.PHONY : Scope_Example_1

# fast build rule for target.
Scope_Example_1/fast:
	$(MAKE) $(MAKESILENT) -f Scope/CMakeFiles/Scope_Example_1.dir/build.make Scope/CMakeFiles/Scope_Example_1.dir/build
.PHONY : Scope_Example_1/fast

#=============================================================================
# Target rules for targets named Scope_Example_2

# Build rule for target.
Scope_Example_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Scope_Example_2
.PHONY : Scope_Example_2

# fast build rule for target.
Scope_Example_2/fast:
	$(MAKE) $(MAKESILENT) -f Scope/CMakeFiles/Scope_Example_2.dir/build.make Scope/CMakeFiles/Scope_Example_2.dir/build
.PHONY : Scope_Example_2/fast

#=============================================================================
# Target rules for targets named Scope_Example_3

# Build rule for target.
Scope_Example_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Scope_Example_3
.PHONY : Scope_Example_3

# fast build rule for target.
Scope_Example_3/fast:
	$(MAKE) $(MAKESILENT) -f Scope/CMakeFiles/Scope_Example_3.dir/build.make Scope/CMakeFiles/Scope_Example_3.dir/build
.PHONY : Scope_Example_3/fast

#=============================================================================
# Target rules for targets named Scope_Example_4

# Build rule for target.
Scope_Example_4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Scope_Example_4
.PHONY : Scope_Example_4

# fast build rule for target.
Scope_Example_4/fast:
	$(MAKE) $(MAKESILENT) -f Scope/CMakeFiles/Scope_Example_4.dir/build.make Scope/CMakeFiles/Scope_Example_4.dir/build
.PHONY : Scope_Example_4/fast

#=============================================================================
# Target rules for targets named Scope_Example_5

# Build rule for target.
Scope_Example_5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Scope_Example_5
.PHONY : Scope_Example_5

# fast build rule for target.
Scope_Example_5/fast:
	$(MAKE) $(MAKESILENT) -f Scope/CMakeFiles/Scope_Example_5.dir/build.make Scope/CMakeFiles/Scope_Example_5.dir/build
.PHONY : Scope_Example_5/fast

#=============================================================================
# Target rules for targets named Functions_Ex_addTogether_GetYesNo

# Build rule for target.
Functions_Ex_addTogether_GetYesNo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Functions_Ex_addTogether_GetYesNo
.PHONY : Functions_Ex_addTogether_GetYesNo

# fast build rule for target.
Functions_Ex_addTogether_GetYesNo/fast:
	$(MAKE) $(MAKESILENT) -f Functions/CMakeFiles/Functions_Ex_addTogether_GetYesNo.dir/build.make Functions/CMakeFiles/Functions_Ex_addTogether_GetYesNo.dir/build
.PHONY : Functions_Ex_addTogether_GetYesNo/fast

#=============================================================================
# Target rules for targets named Array_Ex_Declaring_and_Looping

# Build rule for target.
Array_Ex_Declaring_and_Looping: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_Declaring_and_Looping
.PHONY : Array_Ex_Declaring_and_Looping

# fast build rule for target.
Array_Ex_Declaring_and_Looping/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_Declaring_and_Looping.dir/build.make Arrays/CMakeFiles/Array_Ex_Declaring_and_Looping.dir/build
.PHONY : Array_Ex_Declaring_and_Looping/fast

#=============================================================================
# Target rules for targets named Array_Ex_Outputting_Array

# Build rule for target.
Array_Ex_Outputting_Array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_Outputting_Array
.PHONY : Array_Ex_Outputting_Array

# fast build rule for target.
Array_Ex_Outputting_Array/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_Outputting_Array.dir/build.make Arrays/CMakeFiles/Array_Ex_Outputting_Array.dir/build
.PHONY : Array_Ex_Outputting_Array/fast

#=============================================================================
# Target rules for targets named Array_Ex_Comparing_Arrays

# Build rule for target.
Array_Ex_Comparing_Arrays: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_Comparing_Arrays
.PHONY : Array_Ex_Comparing_Arrays

# fast build rule for target.
Array_Ex_Comparing_Arrays/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_Comparing_Arrays.dir/build.make Arrays/CMakeFiles/Array_Ex_Comparing_Arrays.dir/build
.PHONY : Array_Ex_Comparing_Arrays/fast

#=============================================================================
# Target rules for targets named Array_Ex_Setting_Arrays_Equal

# Build rule for target.
Array_Ex_Setting_Arrays_Equal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_Setting_Arrays_Equal
.PHONY : Array_Ex_Setting_Arrays_Equal

# fast build rule for target.
Array_Ex_Setting_Arrays_Equal/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_Setting_Arrays_Equal.dir/build.make Arrays/CMakeFiles/Array_Ex_Setting_Arrays_Equal.dir/build
.PHONY : Array_Ex_Setting_Arrays_Equal/fast

#=============================================================================
# Target rules for targets named Array_Ex_Summing_and_Averaging

# Build rule for target.
Array_Ex_Summing_and_Averaging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_Summing_and_Averaging
.PHONY : Array_Ex_Summing_and_Averaging

# fast build rule for target.
Array_Ex_Summing_and_Averaging/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_Summing_and_Averaging.dir/build.make Arrays/CMakeFiles/Array_Ex_Summing_and_Averaging.dir/build
.PHONY : Array_Ex_Summing_and_Averaging/fast

#=============================================================================
# Target rules for targets named Array_Ex_Min_Max_Array

# Build rule for target.
Array_Ex_Min_Max_Array: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_Min_Max_Array
.PHONY : Array_Ex_Min_Max_Array

# fast build rule for target.
Array_Ex_Min_Max_Array/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_Min_Max_Array.dir/build.make Arrays/CMakeFiles/Array_Ex_Min_Max_Array.dir/build
.PHONY : Array_Ex_Min_Max_Array/fast

#=============================================================================
# Target rules for targets named Array_Ex_multi_SampleCode

# Build rule for target.
Array_Ex_multi_SampleCode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Ex_multi_SampleCode
.PHONY : Array_Ex_multi_SampleCode

# fast build rule for target.
Array_Ex_multi_SampleCode/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Ex_multi_SampleCode.dir/build.make Arrays/CMakeFiles/Array_Ex_multi_SampleCode.dir/build
.PHONY : Array_Ex_multi_SampleCode/fast

#=============================================================================
# Target rules for targets named Array_multi_part_a

# Build rule for target.
Array_multi_part_a: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_multi_part_a
.PHONY : Array_multi_part_a

# fast build rule for target.
Array_multi_part_a/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_multi_part_a.dir/build.make Arrays/CMakeFiles/Array_multi_part_a.dir/build
.PHONY : Array_multi_part_a/fast

#=============================================================================
# Target rules for targets named Array_multi_part_b

# Build rule for target.
Array_multi_part_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_multi_part_b
.PHONY : Array_multi_part_b

# fast build rule for target.
Array_multi_part_b/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_multi_part_b.dir/build.make Arrays/CMakeFiles/Array_multi_part_b.dir/build
.PHONY : Array_multi_part_b/fast

#=============================================================================
# Target rules for targets named Array_multi_part_c

# Build rule for target.
Array_multi_part_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_multi_part_c
.PHONY : Array_multi_part_c

# fast build rule for target.
Array_multi_part_c/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_multi_part_c.dir/build.make Arrays/CMakeFiles/Array_multi_part_c.dir/build
.PHONY : Array_multi_part_c/fast

#=============================================================================
# Target rules for targets named Array_multi_part_d

# Build rule for target.
Array_multi_part_d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_multi_part_d
.PHONY : Array_multi_part_d

# fast build rule for target.
Array_multi_part_d/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_multi_part_d.dir/build.make Arrays/CMakeFiles/Array_multi_part_d.dir/build
.PHONY : Array_multi_part_d/fast

#=============================================================================
# Target rules for targets named Array_part1

# Build rule for target.
Array_part1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_part1
.PHONY : Array_part1

# fast build rule for target.
Array_part1/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_part1.dir/build.make Arrays/CMakeFiles/Array_part1.dir/build
.PHONY : Array_part1/fast

#=============================================================================
# Target rules for targets named Array_part2

# Build rule for target.
Array_part2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_part2
.PHONY : Array_part2

# fast build rule for target.
Array_part2/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_part2.dir/build.make Arrays/CMakeFiles/Array_part2.dir/build
.PHONY : Array_part2/fast

#=============================================================================
# Target rules for targets named Array_part3

# Build rule for target.
Array_part3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_part3
.PHONY : Array_part3

# fast build rule for target.
Array_part3/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_part3.dir/build.make Arrays/CMakeFiles/Array_part3.dir/build
.PHONY : Array_part3/fast

#=============================================================================
# Target rules for targets named Array_part4

# Build rule for target.
Array_part4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_part4
.PHONY : Array_part4

# fast build rule for target.
Array_part4/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_part4.dir/build.make Arrays/CMakeFiles/Array_part4.dir/build
.PHONY : Array_part4/fast

#=============================================================================
# Target rules for targets named Array_Unit_Tests

# Build rule for target.
Array_Unit_Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Array_Unit_Tests
.PHONY : Array_Unit_Tests

# fast build rule for target.
Array_Unit_Tests/fast:
	$(MAKE) $(MAKESILENT) -f Arrays/CMakeFiles/Array_Unit_Tests.dir/build.make Arrays/CMakeFiles/Array_Unit_Tests.dir/build
.PHONY : Array_Unit_Tests/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named Classes_Ex_Employee_Pay

# Build rule for target.
Classes_Ex_Employee_Pay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Classes_Ex_Employee_Pay
.PHONY : Classes_Ex_Employee_Pay

# fast build rule for target.
Classes_Ex_Employee_Pay/fast:
	$(MAKE) $(MAKESILENT) -f Classes/CMakeFiles/Classes_Ex_Employee_Pay.dir/build.make Classes/CMakeFiles/Classes_Ex_Employee_Pay.dir/build
.PHONY : Classes_Ex_Employee_Pay/fast

#=============================================================================
# Target rules for targets named Classes_Tests

# Build rule for target.
Classes_Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Classes_Tests
.PHONY : Classes_Tests

# fast build rule for target.
Classes_Tests/fast:
	$(MAKE) $(MAKESILENT) -f Classes/CMakeFiles/Classes_Tests.dir/build.make Classes/CMakeFiles/Classes_Tests.dir/build
.PHONY : Classes_Tests/fast

#=============================================================================
# Target rules for targets named Basic_Deck_Tester

# Build rule for target.
Basic_Deck_Tester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Basic_Deck_Tester
.PHONY : Basic_Deck_Tester

# fast build rule for target.
Basic_Deck_Tester/fast:
	$(MAKE) $(MAKESILENT) -f Classes/CMakeFiles/Basic_Deck_Tester.dir/build.make Classes/CMakeFiles/Basic_Deck_Tester.dir/build
.PHONY : Basic_Deck_Tester/fast

#=============================================================================
# Target rules for targets named File_Main

# Build rule for target.
File_Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 File_Main
.PHONY : File_Main

# fast build rule for target.
File_Main/fast:
	$(MAKE) $(MAKESILENT) -f "File Reading and Writing/CMakeFiles/File_Main.dir/build.make" "File Reading and Writing/CMakeFiles/File_Main.dir/build"
.PHONY : File_Main/fast

#=============================================================================
# Target rules for targets named Pointers_Ex_Basic_Usage

# Build rule for target.
Pointers_Ex_Basic_Usage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers_Ex_Basic_Usage
.PHONY : Pointers_Ex_Basic_Usage

# fast build rule for target.
Pointers_Ex_Basic_Usage/fast:
	$(MAKE) $(MAKESILENT) -f Pointers/CMakeFiles/Pointers_Ex_Basic_Usage.dir/build.make Pointers/CMakeFiles/Pointers_Ex_Basic_Usage.dir/build
.PHONY : Pointers_Ex_Basic_Usage/fast

#=============================================================================
# Target rules for targets named Pointers_Ex_Basic_New_Usage

# Build rule for target.
Pointers_Ex_Basic_New_Usage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers_Ex_Basic_New_Usage
.PHONY : Pointers_Ex_Basic_New_Usage

# fast build rule for target.
Pointers_Ex_Basic_New_Usage/fast:
	$(MAKE) $(MAKESILENT) -f Pointers/CMakeFiles/Pointers_Ex_Basic_New_Usage.dir/build.make Pointers/CMakeFiles/Pointers_Ex_Basic_New_Usage.dir/build
.PHONY : Pointers_Ex_Basic_New_Usage/fast

#=============================================================================
# Target rules for targets named Pointers_Ex_Comparison_Issue

# Build rule for target.
Pointers_Ex_Comparison_Issue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers_Ex_Comparison_Issue
.PHONY : Pointers_Ex_Comparison_Issue

# fast build rule for target.
Pointers_Ex_Comparison_Issue/fast:
	$(MAKE) $(MAKESILENT) -f Pointers/CMakeFiles/Pointers_Ex_Comparison_Issue.dir/build.make Pointers/CMakeFiles/Pointers_Ex_Comparison_Issue.dir/build
.PHONY : Pointers_Ex_Comparison_Issue/fast

#=============================================================================
# Target rules for targets named Pointers_Ex_Functions

# Build rule for target.
Pointers_Ex_Functions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers_Ex_Functions
.PHONY : Pointers_Ex_Functions

# fast build rule for target.
Pointers_Ex_Functions/fast:
	$(MAKE) $(MAKESILENT) -f Pointers/CMakeFiles/Pointers_Ex_Functions.dir/build.make Pointers/CMakeFiles/Pointers_Ex_Functions.dir/build
.PHONY : Pointers_Ex_Functions/fast

#=============================================================================
# Target rules for targets named Pointers_Ex_Dynamic_Array_Basic_Usage

# Build rule for target.
Pointers_Ex_Dynamic_Array_Basic_Usage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers_Ex_Dynamic_Array_Basic_Usage
.PHONY : Pointers_Ex_Dynamic_Array_Basic_Usage

# fast build rule for target.
Pointers_Ex_Dynamic_Array_Basic_Usage/fast:
	$(MAKE) $(MAKESILENT) -f Pointers/CMakeFiles/Pointers_Ex_Dynamic_Array_Basic_Usage.dir/build.make Pointers/CMakeFiles/Pointers_Ex_Dynamic_Array_Basic_Usage.dir/build
.PHONY : Pointers_Ex_Dynamic_Array_Basic_Usage/fast

#=============================================================================
# Target rules for targets named Pointers_Ex_Dynamic_Multidimensional_Basic_Usage

# Build rule for target.
Pointers_Ex_Dynamic_Multidimensional_Basic_Usage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers_Ex_Dynamic_Multidimensional_Basic_Usage
.PHONY : Pointers_Ex_Dynamic_Multidimensional_Basic_Usage

# fast build rule for target.
Pointers_Ex_Dynamic_Multidimensional_Basic_Usage/fast:
	$(MAKE) $(MAKESILENT) -f Pointers/CMakeFiles/Pointers_Ex_Dynamic_Multidimensional_Basic_Usage.dir/build.make Pointers/CMakeFiles/Pointers_Ex_Dynamic_Multidimensional_Basic_Usage.dir/build
.PHONY : Pointers_Ex_Dynamic_Multidimensional_Basic_Usage/fast

#=============================================================================
# Target rules for targets named LinkList_Exercise_1_and_2

# Build rule for target.
LinkList_Exercise_1_and_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkList_Exercise_1_and_2
.PHONY : LinkList_Exercise_1_and_2

# fast build rule for target.
LinkList_Exercise_1_and_2/fast:
	$(MAKE) $(MAKESILENT) -f "Linked Lists/CMakeFiles/LinkList_Exercise_1_and_2.dir/build.make" "Linked Lists/CMakeFiles/LinkList_Exercise_1_and_2.dir/build"
.PHONY : LinkList_Exercise_1_and_2/fast

#=============================================================================
# Target rules for targets named LinkList_Tests

# Build rule for target.
LinkList_Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkList_Tests
.PHONY : LinkList_Tests

# fast build rule for target.
LinkList_Tests/fast:
	$(MAKE) $(MAKESILENT) -f "Linked Lists/CMakeFiles/LinkList_Tests.dir/build.make" "Linked Lists/CMakeFiles/LinkList_Tests.dir/build"
.PHONY : LinkList_Tests/fast

#=============================================================================
# Target rules for targets named LinkList_Basic_Test

# Build rule for target.
LinkList_Basic_Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkList_Basic_Test
.PHONY : LinkList_Basic_Test

# fast build rule for target.
LinkList_Basic_Test/fast:
	$(MAKE) $(MAKESILENT) -f "Linked Lists/CMakeFiles/LinkList_Basic_Test.dir/build.make" "Linked Lists/CMakeFiles/LinkList_Basic_Test.dir/build"
.PHONY : LinkList_Basic_Test/fast

#=============================================================================
# Target rules for targets named LinkList_Examples

# Build rule for target.
LinkList_Examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkList_Examples
.PHONY : LinkList_Examples

# fast build rule for target.
LinkList_Examples/fast:
	$(MAKE) $(MAKESILENT) -f "Linked Lists/CMakeFiles/LinkList_Examples.dir/build.make" "Linked Lists/CMakeFiles/LinkList_Examples.dir/build"
.PHONY : LinkList_Examples/fast

#=============================================================================
# Target rules for targets named LinkListClass

# Build rule for target.
LinkListClass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkListClass
.PHONY : LinkListClass

# fast build rule for target.
LinkListClass/fast:
	$(MAKE) $(MAKESILENT) -f "Linked Lists/CMakeFiles/LinkListClass.dir/build.make" "Linked Lists/CMakeFiles/LinkListClass.dir/build"
.PHONY : LinkListClass/fast

catch/catch_main.o: catch/catch_main.cpp.o
.PHONY : catch/catch_main.o

# target to build an object file
catch/catch_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catch2_main_DO_NOT_RUN.dir/build.make CMakeFiles/catch2_main_DO_NOT_RUN.dir/catch/catch_main.cpp.o
.PHONY : catch/catch_main.cpp.o

catch/catch_main.i: catch/catch_main.cpp.i
.PHONY : catch/catch_main.i

# target to preprocess a source file
catch/catch_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catch2_main_DO_NOT_RUN.dir/build.make CMakeFiles/catch2_main_DO_NOT_RUN.dir/catch/catch_main.cpp.i
.PHONY : catch/catch_main.cpp.i

catch/catch_main.s: catch/catch_main.cpp.s
.PHONY : catch/catch_main.s

# target to generate assembly for a file
catch/catch_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/catch2_main_DO_NOT_RUN.dir/build.make CMakeFiles/catch2_main_DO_NOT_RUN.dir/catch/catch_main.cpp.s
.PHONY : catch/catch_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Array_Ex_Comparing_Arrays"
	@echo "... Array_Ex_Declaring_and_Looping"
	@echo "... Array_Ex_Min_Max_Array"
	@echo "... Array_Ex_Outputting_Array"
	@echo "... Array_Ex_Setting_Arrays_Equal"
	@echo "... Array_Ex_Summing_and_Averaging"
	@echo "... Array_Ex_multi_SampleCode"
	@echo "... Array_Unit_Tests"
	@echo "... Array_multi_part_a"
	@echo "... Array_multi_part_b"
	@echo "... Array_multi_part_c"
	@echo "... Array_multi_part_d"
	@echo "... Array_part1"
	@echo "... Array_part2"
	@echo "... Array_part3"
	@echo "... Array_part4"
	@echo "... Basic_Deck_Tester"
	@echo "... Basic_Input_Output"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... Classes_Ex_Employee_Pay"
	@echo "... Classes_Tests"
	@echo "... File_Main"
	@echo "... Functions_Ex_addTogether_GetYesNo"
	@echo "... LinkListClass"
	@echo "... LinkList_Basic_Test"
	@echo "... LinkList_Examples"
	@echo "... LinkList_Exercise_1_and_2"
	@echo "... LinkList_Tests"
	@echo "... Pointers_Ex_Basic_New_Usage"
	@echo "... Pointers_Ex_Basic_Usage"
	@echo "... Pointers_Ex_Comparison_Issue"
	@echo "... Pointers_Ex_Dynamic_Array_Basic_Usage"
	@echo "... Pointers_Ex_Dynamic_Multidimensional_Basic_Usage"
	@echo "... Pointers_Ex_Functions"
	@echo "... Scope_Example_1"
	@echo "... Scope_Example_2"
	@echo "... Scope_Example_3"
	@echo "... Scope_Example_4"
	@echo "... Scope_Example_5"
	@echo "... String_Examples"
	@echo "... String_Practice_Basic_Tests"
	@echo "... String_Practice_Unit_Tests"
	@echo "... String_cstring_Examples"
	@echo "... Types_and_Casting_Debugger_Example"
	@echo "... Types_and_Casting_Examples"
	@echo "... _Hello_World_IDE_Test_"
	@echo "... catch2_main_DO_NOT_RUN"
	@echo "... cin_cout_Exercise_1"
	@echo "... cin_cout_Exercise_2"
	@echo "... catch/catch_main.o"
	@echo "... catch/catch_main.i"
	@echo "... catch/catch_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

